### ISSUE TITLE
我是windows系统，运行 的时候出现以下问题，貌似缺少“./log/wxapi-log.log”文件orWindows路径出错

### ISSUE THREAD

**Issue by TurkishHan** [ChaosCoffee/wxRobot#1]
(base) PS C:\ProgramData\Anaconda3\wxRobot-master>  python ./wx_robot.py
Traceback (most recent call last):
  File "./wx_robot.py", line 8, in <module>
    from api.wxapi import *
  File "C:\ProgramData\Anaconda3\wxRobot-master\api\__init__.py", line 1, in <module>
    from .wxapi import logger
  File "C:\ProgramData\Anaconda3\wxRobot-master\api\wxapi.py", line 10, in <module>
    fh = logging.FileHandler(".\\log\\wxapi-log.log") # 文件对象
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\wxRobot-master\\log\\wxapi-log.log'
(base) PS C:\ProgramData\Anaconda3\wxRobot-master>

**Comment by ChaosCoffee** [comment]
这是个日志记录文件目录，可以在运行目录下建立`log`空文件夹解决。

**Comment by TurkishHan** [comment]
感谢您！我这样做了发现还是有如下错误：






------------------ 原始邮件 ------------------
发件人: "chaoscoffee"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 下午2:53
收件人: "ChaosCoffee/wxRobot"<wxRobot@noreply.github.com>;
抄送: "zhs"<1551218144@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ChaosCoffee/wxRobot] 我是windows系统，运行 的时候出现以下问题，貌似缺少“./log/wxapi-log.log”文件orWindows路径出错 (#1)




这是个日志记录文件目录，可以在运行目录下建立log空文件夹解决。
